import { isResolvedConfig } from '../config/validate';
import type { ResolvedConfig } from '../config/schema';
import { MAX_TRAVEL } from '../keyboard/analog-report';

/**
 * Bumped when the shape on the wire changes, so that an overlay left open
 * across a deployment is told to reload rather than quietly rendering nothing
 * it recognises (spec §11, `onForeignVersion`).
 *
 * 4 since 2026-08-25: `restVisibility` became a per-key property, so it left
 * the root of `ResolvedConfig` for `keys[].style`. A v3 overlay validates the
 * root field and rejects the whole configuration; a v4 overlay handed a v3
 * message would read `undefined` on every key. Neither can be told apart from
 * a broken overlay without this number.
 */
export const PROTOCOL_VERSION = 4;

/** [matrix index, travel 0..1023, actuation]. `active` is always transmitted. */
export type FrameKey = readonly [id: number, travel: number, active: 0 | 1];

/**
 * `id` is generated by the overlay and is a deliberate deviation from spec §6,
 * which describes these two without one. Counting the connected overlays is
 * impossible without something to tell them apart, and the spec asks for that
 * count as well.
 */
export type HelloMessage = {
  v: typeof PROTOCOL_VERSION;
  t: 'hello';
  id: string;
  /**
   * The overlay is in an ordinary browser rather than in OBS (spec §16.7).
   *
   * Opening `overlay.html` to check that it works took the count from one to
   * two, and the figure was not wrong — that page *is* an overlay. It became
   * useless the instant anyone used it: no way left to tell whether the one in
   * OBS was among them. **The diagnostic tool broke the diagnostic.**
   */
  browser: boolean;
};
export type BeatMessage = {
  v: typeof PROTOCOL_VERSION;
  t: 'beat';
  id: string;
  browser: boolean;
};
/**
 * Sent as the overlay page goes away. Expiry alone cannot replace it: a reload
 * draws a new id, so the page that left keeps being counted next to the one
 * that replaced it. The timeout stays as the net for departures that give no
 * warning — a crash, or OBS being killed.
 */
export type ByeMessage = { v: typeof PROTOCOL_VERSION; t: 'bye'; id: string };
/**
 * `from` is the capture page that sent this, and it is the counterpart of the
 * `id` the overlay puts on its own three messages: both ends of the bus now
 * sign what they say.
 *
 * Nothing reads it to route anything — the overlay obeys every configuration it
 * is given, as before. It exists so that a capture page can tell its own
 * broadcast from a second one's. Twenty tabs left open all publish onto the
 * same bus, the overlay follows whichever spoke last, and until this field
 * there was no way for anyone to notice: each page counted only its own frames
 * and dropped the others in silence.
 */
export type ConfigMessage = {
  v: typeof PROTOCOL_VERSION;
  t: 'config';
  from: string;
  config: ResolvedConfig;
};
export type FrameMessage = {
  v: typeof PROTOCOL_VERSION;
  t: 'frame';
  from: string;
  k: FrameKey[];
};

export type OverlayMessage = HelloMessage | BeatMessage | ByeMessage | ConfigMessage | FrameMessage;

const KNOWN_TYPES = ['hello', 'beat', 'bye', 'config', 'frame'] as const;
/** The three the overlay sends about itself, all keyed by its id. */
const PRESENCE_TYPES: readonly string[] = ['hello', 'beat', 'bye'];
/** The two the capture page sends outwards, all signed with its own name. */
const BROADCAST_TYPES: readonly string[] = ['config', 'frame'];

export function envelope(message: OverlayMessage): { heOverlay: OverlayMessage } {
  return { heOverlay: message };
}

function isFrameKey(value: unknown): value is FrameKey {
  if (!Array.isArray(value) || value.length !== 3) return false;
  const [id, travel, active] = value;
  // Finite is not enough: this is a trust boundary, and the protocol defines
  // both fields precisely. `id` indexes a matrix position — never a fraction,
  // never negative — and `travel` is a uint16 shifted right by 6 bits
  // (analog-report.ts), so `MAX_TRAVEL` bounds it by construction on the real
  // device. Anything outside either range cannot come from a capture page
  // speaking the protocol honestly, so it is refused here rather than trusted
  // to whatever `scene.ts`'s own clamp happens to do with it.
  return (
    Number.isInteger(id) &&
    id >= 0 &&
    Number.isFinite(travel) &&
    travel >= 0 &&
    travel <= MAX_TRAVEL &&
    (active === 0 || active === 1)
  );
}

/**
 * Returns the message when it matches our version and shape, `null` otherwise.
 * Each page then silently ignores the types that do not concern it (spec §6).
 *
 * The shape is checked, not assumed: this is a trust boundary. Any client
 * connected to the same obs-websocket can emit a CustomEvent under our key, and
 * a frame whose `k` is missing would blow up the overlay's next render — a
 * failure nobody watching the configuration screen would ever notice.
 */
export function parseMessage(payload: unknown): OverlayMessage | null {
  if (typeof payload !== 'object' || payload === null) return null;

  const inner = (payload as { heOverlay?: unknown }).heOverlay;
  if (typeof inner !== 'object' || inner === null) return null;

  const { v, t } = inner as { v?: unknown; t?: unknown };
  if (v !== PROTOCOL_VERSION) return null;
  if (typeof t !== 'string' || !KNOWN_TYPES.includes(t as (typeof KNOWN_TYPES)[number]))
    return null;

  if (t === 'frame') {
    const { k } = inner as { k?: unknown };
    if (!Array.isArray(k) || !k.every(isFrameKey)) return null;
  }

  if (t === 'config') {
    const { config } = inner as { config?: unknown };
    // Fully checked, not merely "an object". The plan argued both sides are
    // built from the same repository — true of the sender we intend, and
    // nothing to do with the channel. `buildScene` reads `keys.filter` and
    // `style.radius` without a fallback, so a config shaped wrong takes the
    // overlay down for the rest of the stream.
    if (!isResolvedConfig(config)) return null;
  }

  if (PRESENCE_TYPES.includes(t)) {
    const { id } = inner as { id?: unknown };
    // An unusable id would register as an overlay keyed `undefined`: one
    // phantom listener the capture page counts forever, and the status bar
    // saying someone is watching when nobody is. On a bye it cuts the other
    // way — that is the message which removes a listener.
    if (typeof id !== 'string' || id === '') return null;
  }

  if (BROADCAST_TYPES.includes(t)) {
    const { from } = inner as { from?: unknown };
    // Required rather than defaulted, and for a sharper reason than `id`. A
    // capture page compares this against its own name to know whether it is
    // alone on the bus; a missing one would have to compare as *something*, and
    // whichever way it fell it would answer that question wrongly for one of
    // the two pages.
    if (typeof from !== 'string' || from === '') return null;
  }

  if (t === 'hello' || t === 'beat') {
    const { browser } = inner as { browser?: unknown };
    // Required rather than defaulted: a missing flag would read as `false` and
    // report an overlay inside OBS that nobody there can see. `bye` is exempt —
    // it says who is leaving, and where it was makes no difference to that.
    if (typeof browser !== 'boolean') return null;
  }

  return inner as OverlayMessage;
}

/**
 * The protocol version of a message plainly meant for us that we cannot read.
 *
 * `parseMessage` returns `null` for these, which is right for processing and
 * useless for diagnosis: an overlay left open across a deployment goes quiet
 * with nothing to say why. This serves the journal, never the pipeline.
 *
 * Answers for older versions as readily as newer ones — the common case is an
 * overlay that is *behind*, not ahead.
 */
export function foreignVersion(payload: unknown): number | null {
  if (typeof payload !== 'object' || payload === null) return null;

  const inner = (payload as { heOverlay?: unknown }).heOverlay;
  // Someone else's custom event is not our overlay on a strange protocol.
  // Saying it is would send someone reloading a page that was never ours.
  if (typeof inner !== 'object' || inner === null) return null;

  const { v } = inner as { v?: unknown };
  return typeof v === 'number' && v !== PROTOCOL_VERSION ? v : null;
}
